{% set name = "spec-kit" %}
{% set version = "0.1.5" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/github/spec-kit/archive/v{{ version }}.tar.gz
  sha256: 1eac4c4a9b168a576a6feac7e9376da74c1ea7c7e46b755211d6b7f71e9c1d55

build:
  entry_points:
    - specify = specify_cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  script_env:
    - PYTHONIOENCODING=utf8
    - PYTHONUTF8=1
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - click >=8.1
    - python >={{ python_min }},<4.0
    - typer
    - rich
    - httpx
    # https://github.com/encode/httpx/blob/master/pyproject.toml#L51
    - socksio ==1
    - platformdirs
    - readchar
    - truststore >=0.10.4
    - pyyaml >=6.0
    - packaging >=23.0

test:
  imports:
    - specify_cli
  commands:
    - specify --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Specify CLI, part of GitHub Spec Kit. A tool to bootstrap your projects for Spec-Driven Development (SDD).
  license: MIT
  license_file: LICENSE
  home: https://github.com/github/spec-kit

extra:
  recipe-maintainers:
    - rxm7706
